services:
  dev:
    build:
      context: .
      dockerfile: docker/dockerfile.dev
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    volumes:
      - .:/app
    env_file:
      - .env.dev


volumes:
  postgres_data:
